<?xml version="1.0" encoding="UTF-8"?>
<!--This work by Eucalyptus Systems is licensed under a Creative Commons Attribution-ShareAlike 3.0 Unported License. See the accompanying LICENSE file for more information.-->
<!DOCTYPE concept PUBLIC "-//OASIS//DTD DITA Concept//EN" "concept.dtd">
<concept id="rn_issues_euca2ools_3.0.2">
 <title>Known Issues</title>
 <shortdesc/>
 <conbody>
  <p>The following table lists behavioral changes and known issues that exist in Euca2ools 3.0.2.
   Please contact Eucalyptus support for workarounds or prescriptive guidance for these issues. You
   can use the support portal <xref href="https://engage.eucalyptus.com" scope="external"
    format="html">https://engage.eucalyptus.com</xref> or email us directly at <xref
    href="mailto:support@eucalyptus.com" scope="external" format="email"
    >support@eucalyptus.com</xref>.</p>
  <table>
   <tgroup cols="2">
    <thead>
     <row>
      <entry>Issue</entry>
      <entry>Description</entry>
     </row>
    </thead>
    <tbody>
     <row>
      <entry>Euca2ools crashes when non-ASCII character is passed (<xref format="html"
        href="https://eucalyptus.atlassian.net/browse/TOOLS-385">TOOLS-385</xref>)</entry>
      <entry>Occurs when the locale settings prevent python from encoding all of the characters in a
       command's output. Work around this by explicitly setting the <codeph>LC_CTYPE</codeph>
       environment variable to a locale that is capable of handling the characters in use, such as
        <codeph>en_US.UTF-8</codeph>. </entry>
     </row>
    </tbody>
   </tgroup>
  </table>
 </conbody>
</concept>
